### ISSUE TITLE
executing  script throws  json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by jensstruemper** [mitsuhiko/flatex-pdf-download#3] opened 2022-03-28 19:43 UTC
python3.9 flatex-fetch.py -u bla -p blub

Traceback (most recent call last):
  File "/Users/jens/Development/flatex-pdf-download/flatex-fetch.py", line 266, in <module>
    cli()
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jens/Development/flatex-pdf-download/flatex-fetch.py", line 262, in cli
    fetcher.download_all(output, days=days)
  File "/Users/jens/Development/flatex-pdf-download/flatex-fetch.py", line 158, in download_all
    for url in self.iter_all_download_urls(**kwargs):
  File "/Users/jens/Development/flatex-pdf-download/flatex-fetch.py", line 143, in iter_all_download_urls
    for url in self.iter_download_urls(start_date, end_date):
  File "/Users/jens/Development/flatex-pdf-download/flatex-fetch.py", line 109, in iter_download_urls
    self._archive_list_request({"applyFilterButton.clicked": "true", **data})
  File "/Users/jens/Development/flatex-pdf-download/flatex-fetch.py", line 89, in _archive_list_request
    return self._request(
  File "/Users/jens/Development/flatex-pdf-download/flatex-fetch.py", line 77, in _request
    json = resp.json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mitsuhiko** [comment] 2022-12-10 21:05
Yeah I'm not sure what's going on here. There seems to be a change that makes Flatex return 503 when interfacing with it. The requests still seem to match what the browser is doing but presumably they are unhappy with what I'm sending to it.

**Comment by kaulex99** [comment] 2023-01-02 11:54
Is there a plan for fixing this issue?

**Comment by mitsuhiko** [comment] 2023-01-02 22:10
@kaulex99 the issue is that flatex currently loves locking me out of the account trying to fix it, and i rather not upset them. So no real path forward for fixing it. :(

**Comment by mitsuhiko** [comment] 2023-01-17 22:04
Fixed by #4

**Closed by mitsuhiko** 2023-01-17 22:04 UTC
